### ISSUE TITLE
한글좀

### ISSUE THREAD

**Issue by ddtt786GH** [xibotlab/logg#5]
ㅠ

**Comment by baboseojin** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by xibotmoon** [comment]
안녕하세요, @ddtt786님.
해당 프로젝트는 내국인 이외 외국인분들께서도 사용이 가능하도록 `README.md`를 영어로 구성하고 있습니다.
다만 Issue나 Project 탭은 한글로 구성하고 있으니 이 점 참고해주시기 바랍니다.

감사합니다.
